### ISSUE TITLE
Unable to edit data on line chart

### ISSUE THREAD

**Issue by david23zhu** [gitbrent/PptxGenJS#122]
Hello,

This library is amazing and has been a great help to us! Thanks for the great work!

Recently we encountered a issue when we try to Edit Data on the generated line chart, the line chart will disappear, and there is no data found in the opened excel window, it works for bar chart and pie chart.

Examples can be found in PptxGenJS-master Demo Examples. Please help, many thanks.

**Comment by gitbrent** [comment]
Hi @david23zhu,

Thanks for opening an issue for this - and thanks for the kind words!

The library was not creating the underlying Excel workbooks correctly for both `LINE` and `AREA` charts.  That has been fixed in the newest codebase.

Please give it a try and let me know if everything works now.

**Comment by david23zhu** [comment]
Hello Brent,

Thanks for your fix. I have tried the new code unfortunately it's still not working for Line Chart and Area Chart, there is no new excel window showing up after selecting Edit Data.

**Comment by gitbrent** [comment]
Hi @david23zhu 

Thanks for testing.  All chart formats are editable now.

**Comment by david23zhu** [comment]
@gitbrent Many thnaks!! It works wonderfully now!
