### ISSUE TITLE
Wrong type definition for placeholder `type` property

### ISSUE THREAD

**Issue by lukevella** [gitbrent/PptxGenJS#921]
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.4.0]

### Desired Behavior

The following code should work fine:

```ts
const pptx = new PptxGenJs()

pptx.defineSlideMaster({
    title: "PLACEHOLDER_SLIDE",
    objects: [
        {
            placeholder: {
                options: { name: "body", type: "body", x: 0.6, y: 1.5, w: 12, h: 5.25 },
                text: "(custom placeholder text!)",
            },
        },
    ],
});
```

### Observed Behavior

We get the following typescript error:

<img width="1183" alt="Screenshot 2021-03-22 at 14 58 22" src="https://user-images.githubusercontent.com/676849/112010288-148d8c80-8b1f-11eb-9e2a-9a06fd8df04f.png">

I observed that we can satisfy typescript by passing `PptxGenJs.PLACEHOLDER_TYPES.body` as `type` however this causes a runtime error. Seems like the type definition  for `PlaceholderProps.type` is just wrong.

### Steps to Reproduce
Copy and paste the snippet above in to a typeescript project.

**Comment by jmroon** [comment]
I'm having similar issues.

    import PptxGenJS from "pptxgenjs";


I can create a new instance:
    var pptx = new PptxGenJS();


But even though my IDE thinks I can access the namespaced enums, it seems as though PptxGenJs only allows me to access its constructor and not the namespaced enums as follows:
    PptxGenJS.PLACEHOLDER_TYPES.title


Am I doing something wrong here?

**Comment by jmroon** [comment]
This is not ideal, but you can at least bypass the issue with the following:

    type: "title" as pptxgen.PLACEHOLDER_TYPES

**Comment by jmroon** [comment]
This is the result from the transpilation:
    type: pptxgenjs__WEBPACK_IMPORTED_MODULE_1__[\"default\"].PLACEHOLDER_TYPES.title

Looks like maybe only the default export gets imported, and the namespace gets ignored.

**Comment by gitbrent** [comment]
@lukevella - Good catch. The type needs to be exposed correctly like `ChartType` etc.

Fixed in head:
![Screen Shot 2021-03-24 at 00 14 43](https://user-images.githubusercontent.com/7218970/112259263-fa929d80-8c35-11eb-94a4-309b743d1646.png)

Now it can be used without issues:
![Screen Shot 2021-03-24 at 00 12 14](https://user-images.githubusercontent.com/7218970/112259253-f6668000-8c35-11eb-99fe-89c1b945fc30.png)

**Comment by gitbrent** [comment]
@lukevella @jmroon - you're welcome to test the fix by patching your node_modules/pptxgenjs/types/index.d.ts - just add this as shown above on line 29

```typescript
readonly PlaceholderType: typeof PptxGenJS.PLACEHOLDER_TYPES
```

**Comment by lukevella** [comment]
@gitbrent That change does not seem to fix the issue for me. What does fix it is the following change:

```diff
export interface PlaceholderProps {
  name: string
- type: PLACEHOLDER_TYPES
+ type: keyof typeof PLACEHOLDER_TYPES
  x: Coord
  y: Coord
  w: Coord
  h: Coord
}
```

**Comment by gitbrent** [comment]
@lukevella - okay, there's yet another change needed - we're using `type` in other defs, but an `enum` here, hence the issue.

Added:
```typescript
    export type PLACEHOLDER_TYPE = 'title' | 'body' | 'pic' | 'chart' | 'tbl' | 'media'
```

Updated:
```typescript
    export interface PlaceholderProps {
        name: string
        type: PLACEHOLDER_TYPE
        x: Coord
        y: Coord
        w: Coord
        h: Coord
    }
```
